version: '3.8'

services:
  db:
    image: mysql:8.0 
    container_name: analytics_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password 
      MYSQL_DATABASE: my_ad_data 
      MYSQL_USER: me
      MYSQL_PASSWORD: artem228
    ports:
      - "3306:3306" 
    volumes:
      - mysql_data:/var/lib/mysql 
    healthcheck: 
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uuser", "-ppassword"]
      interval: 5s
      timeout: 10s
      retries: 5


  redis:
    image: "redis:alpine"
    container_name: analytics_redis
    ports:
      - "6379:6379" 
    volumes:
      - redis_data:/data 
    restart: always 

  # FastAPI Application Service
  api:
    build: . 
    container_name: analytics_api
    ports:
      - "8000:8000"
    depends_on: 
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    environment: 
      REDIS_HOST: redis 
      REDIS_PORT: 6379
      MYSQL_HOST: db 
      MYSQL_USER: me
      MYSQL_PASSWORD: artem228
      MYSQL_DATABASE: my_ad_data
    restart: always 

volumes:
  mysql_data:
  redis_data:
